.TH Ascii
.SH NAME
Ascii (built by Trishit Dedhia) version 1.0.1
.SH SYPNOSIS
.P
karla ascii --version
.P
karla ascii --help
.P
\fBkarla ascii\fP [OPTIONS] \fB<image>\fP
.SH DESCRIPTION
.P
Ascii is part of the imaging libraries of Karla 1.0.
.P
Ascii takes in an image as its primary input and converts its to an ascii test art.
.SH OPTION
.SS -a | --ascii
.P
Requires a string as an input. Uses the characters of the string to print the image.
.P
For "invert" the program reverses its default list of ascii characters.
.P
For "extended" the program uses all ascii characters and maps them acoording to their brightness.
.SS -o | --output
.P
Requires a name. Specifies the file name to which the output should be redirected.
.SS -s | --save
.P
Requires a name. Specifies the file name to which the image of the ascii art will be saved
.SS -w | --width
.P
Requires a positive integer. Specifies the number of ascii characters in the width of the image.
.SH SEE ALSO
karla(1)
.SH GITHUB AND DOCUMENTATION
.SS Karla
\fIhttps://github.com/trishitdedhia/karla\fP
.SS Ascii
\fIhttps://github.com/trishitdedhia/ascii\fP
  
